[
  {
    "time": "2025-08-30 02:09:28",
    "ip": "127.0.0.1",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0",
    "activity": "OpenAIHTTP",
    "details": "401 {\n    \"error\": {\n        \"message\": \"Incorrect API key provided: sk-xxxxx*******************xxxx. You can find your API key at https://platform.openai.com/account/api-keys.\",\n        \"type\": \"invalid_"
  },
  {
    "time": "2025-08-30 02:09:30",
    "ip": "127.0.0.1",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0",
    "activity": "OpenAIHTTP",
    "details": "401 {\n    \"error\": {\n        \"message\": \"Incorrect API key provided: sk-xxxxx*******************xxxx. You can find your API key at https://platform.openai.com/account/api-keys.\",\n        \"type\": \"invalid_"
  },
  {
    "time": "2025-08-30 02:09:34",
    "ip": "127.0.0.1",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0",
    "activity": "OllamaError",
    "details": "HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F4EFE2270>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"
  },
  {
    "time": "2025-08-30 02:10:07",
    "ip": "127.0.0.1",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0",
    "activity": "OpenAIHTTP",
    "details": "401 {\n    \"error\": {\n        \"message\": \"Incorrect API key provided: sk-xxxxx*******************xxxx. You can find your API key at https://platform.openai.com/account/api-keys.\",\n        \"type\": \"invalid_"
  },
  {
    "time": "2025-08-30 02:10:08",
    "ip": "127.0.0.1",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0",
    "activity": "OpenAIHTTP",
    "details": "401 {\n    \"error\": {\n        \"message\": \"Incorrect API key provided: sk-xxxxx*******************xxxx. You can find your API key at https://platform.openai.com/account/api-keys.\",\n        \"type\": \"invalid_"
  },
  {
    "time": "2025-08-30 02:10:12",
    "ip": "127.0.0.1",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36 Edg/139.0.0.0",
    "activity": "OllamaError",
    "details": "HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F4F00E350>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))"
  }
]